[package]
name = "lore_render"
version = "0.1.0"
authors = ["soer"]
edition = "2018"

[dependencies]
nalgebra = "0.16"
glutin = "0.22.0-alpha1"
gl = "0.6.0"
slab = "0.4.2"
cgmath = "0.17.0"
memoffset = "0.5.1"
image = "0.22.0"
lore_mesh = { path = "../lore_mesh"}
